

services:
  web:
    build: /mnt/c/Users/T540p/Desktop/amebo/amebo
    command: python manage.py 0.0.0.0:8000
    volumes:
      - ./amebo/amebo/:/usr/src/amebo/amebo/
    ports:
      - 8000:8000
      # this file create is you are in dev or prod and ur secret keys
    env_file:
      - ./.env.dev
  