import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import Headers from "./components/Navbar/Headers";
import Modal from "./components/modals/Modals";
import LoginModal from "./components/modals/Login";
import SignUpModal from "./components/modals/SignUpModal";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Amebonaija",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
// WE USE THIS FUNCTION TO ADD CONTENT ON THE PAGE
  const content = (
    <p>page Content is here </p>
  
  )
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>

        <Navbar/>
       
        {/* <Headers /> */}
       

        <div className="pt-32">
        {children}
        </div>
{/* we will do some testing on this when we are working with the backend login  */}
        {/* <Modal 
        label='Modaltest'
        content={content}
        isOpen={false}
        /> */}
        <LoginModal />
        <SignUpModal />
      </body>
    </html>
  );
}
