

services:
  web:
    build: /home/amebo/amebo
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./amebo/amebo/:/usr/src/amebo/amebo/

    ports:
      - 8000:8000
      # this file create is you are in dev or prod and ur secret keys
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=djangoblog

volumes:
  postgres_data:

  